### ISSUE TITLE
Не работает удаление в списках тестов

### ISSUE THREAD

**Issue by Metastasis** [ita1001/tests#12]
Не работает удаление в "Список тестов->Любой тест->Удалить любой вопрос". Должно всплывать окно с Да\Нет (метод confirm() в JS). Надо разобраться.
1. Рабочая ветка - tests-8
2. [Файл в котором проблема](https://github.com/ita1001/tests/blob/master/admin/test_edit.php)

**Comment by meowme0w** [comment]
мы в тебя верим, чувак

**Comment by Metastasis** [comment]
я тесты пишу

**Comment by meowme0w** [comment]
у кого еще задания не осталось?
